version: "3.8"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: default
      MYSQL_DATABASE: user

  orm-user-service:
    restart: always
    build:
      context: ./ORM-user-service
      dockerfile: Dockerfile
    container_name: orm-user-service
    volumes:
      - ./ORM-user-service:/app
    ports:
      - "8002:8002"
    env_file:
      - .env
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    links:
      - mysql
    depends_on:
      - mysql
      
  user-service:
    restart: always
    build: ./user-service
    container_name: user-service
    volumes:
      - ./user-service:/app
    env_file:
      - .env
    environment:
      - ORM-USER-SERVICE=${ORM_USER_SERVICE}
      - TEST=$TEST
    ports:
      - "8001:8001"
    links:
      - orm-user-service
    depends_on:
      - orm-user-service

  diag-service:
    restart: always
    build: ./diagonostic-service
    container_name: diagonostic-service
    volumes:
      - ./diagonostic-service:/app
    env_file:
      - .env
    environment:
      - ORM-DIAG-SERVICE=${ORM_DIAG_SERVICE}
      - TEST=$TEST
    ports:
      - "8003:8003"
    links:
      - orm-diag-service
    depends_on:
      - orm-diag-service
      
  orm-diag-service:
    restart: always
    build:
      context: ./ORM-diagonostic-service
      dockerfile: Dockerfile
    container_name: orm-diagonostic-service
    volumes:
      - ./ORM-diagonostic-service:/app
    ports:
      - "8004:8004"
    env_file:
      - .env
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    links:
      - mysql
    depends_on:
      - mysql
      
