version: "3.8"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: default
      MYSQL_DATABASE: user

  orm-user-service:
    restart: always
    build:
      context: ./ORM-user-service
      dockerfile: Dockerfile
    container_name: orm-user-service
    volumes:
      - ./ORM-user-service:/app
    ports:
      - "8002:8002"
    env_file:
      - .env
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - USER_DATABASE_NAME=${USER_DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASE=${REDIS_DATABASE}
    links:
      - mysql
    depends_on:
      - mysql
      
  user-service:
    restart: always
    build: ./user-service
    container_name: user-service
    volumes:
      - ./user-service:/app
    env_file:
      - .env
    environment:
      - ORM-USER-SERVICE=${ORM_USER_SERVICE}
      - TEST=$TEST
    ports:
      - "8001:8001"
    links:
      - orm-user-service
    depends_on:
      - orm-user-service
      - redis

  symptom-service:
    restart: always
    build: ./symptom-service
    container_name: symptom-service
    volumes:
      - ./symptom-service:/app
    env_file:
      - .env
    environment:
      - ORM-SYMPTOM-SERVICE=${ORM_SYMPTOM_SERVICE}
      - TEST=$TEST
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASE=${REDIS_DATABASE}
    ports:
      - "8003:8003"
    links:
      - orm-symptom-service
    depends_on:
      - orm-symptom-service
      - redis
      
  orm-symptom-service:
    restart: always
    build:
      context: ./ORM-symptom-service
      dockerfile: Dockerfile
    container_name: orm-symptom-service
    volumes:
      - ./ORM-symptom-service:/app
    ports:
      - "8004:8004"
    env_file:
      - .env
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - SYMPTOM_DATABASE_NAME=${SYMPTOM_DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    links:
      - mysql
    depends_on:
      - mysql
    
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
