services:
  user-service:
    restart: always
    build: ./user-service
    container_name: user-service
    volumes:
      - ./user-service:/app
    env_file:
      - .env
    environment:
      - ORM_USER_SERVICE=${ORM_USER_SERVICE}
      - TEST=$TEST
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    links:
      - orm-user-service
    depends_on:
      - orm-user-service
      - redis

  orm-user-service:
    restart: always
    build:
      context: ./ORM-user-service
      dockerfile: Dockerfile
    container_name: orm-user-service
    volumes:
      - ./ORM-user-service:/app
    ports:
      - "${ORM_USER_SERVICE_PORT}:${ORM_USER_SERVICE_PORT}"
    env_file:
      - .env
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - USER_DATABASE_NAME=${USER_DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASE=${REDIS_DATABASE}
    links:
      - mysql
    depends_on:
      - mysql

  symptom-service:
    restart: always
    build: ./symptom-service
    container_name: symptom-service
    volumes:
      - ./symptom-service:/app
    env_file:
      - .env
    environment:
      - ORM_SYMPTOM_SERVICE=${ORM_SYMPTOM_SERVICE}
      - TEST=$TEST
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASE=${REDIS_DATABASE}
    ports:
      - "${SYMPTOM_SERVICE_PORT}:${SYMPTOM_SERVICE_PORT}"
    links:
      - orm-symptom-service
      - redis
    depends_on:
      - orm-symptom-service
      - redis
      
  orm-symptom-service:
    restart: always
    build:
      context: ./ORM-symptom-service
      dockerfile: Dockerfile
    container_name: orm-symptom-service
    volumes:
      - ./ORM-symptom-service:/app
    ports:
      - "${ORM_SYMPTOM_SERVICE_PORT}:${ORM_SYMPTOM_SERVICE_PORT}"
    env_file:
      - .env
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - SYMPTOM_DATABASE_NAME=${SYMPTOM_DATABASE_NAME}
    links:
      - mongodb
    depends_on:
      - mongodb

  community-service:
    restart: always
    build: ./community-service
    container_name: community-service
    volumes:
      - ./community-service:/app
    env_file:
      - .env
    environment:
      - ORM_METACOMMUNITY_SERVICE=${ORM_METACOMMUNITY_SERVICE}
      - ORM_MEMBER_SERVICE=${ORM_MEMBER_SERVICE}
      - ORM_POST_SERVICE=${ORM_POST_SERVICE}
      - ORM_COMMENT_SERVICE=${ORM_COMMENT_SERVICE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASE=${REDIS_DATABASE}
    ports:
      - "${COMMUNITY_SERVICE_PORT}:${COMMUNITY_SERVICE_PORT}"
    links:
      - orm-metacommunity-service
      - orm-member-service
      - orm-post-service
      - orm-comment-service
      - redis
    depends_on:
      - orm-metacommunity-service
      - orm-member-service
      - orm-post-service
      - orm-comment-service
      - redis

  orm-metacommunity-service:
    restart: always
    build:
      context: ./ORM-metacommunity-service
      dockerfile: Dockerfile
    container_name: orm-metacommunity-service
    volumes:
      - ./ORM-metacommunity-service:/app
    ports:
      - "${ORM_METACOMMUNITY_SERVICE_PORT}:${ORM_METACOMMUNITY_SERVICE_PORT}"
    env_file:
      - .env
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - COMMUNITY_DATABASE_METACOMMUNITY=${COMMUNITY_DATABASE_METACOMMUNITY}
    links:
      - mongodb
    depends_on:
      - mongodb

  orm-member-service:
    restart: always
    build:
      context: ./ORM-member-service
      dockerfile: Dockerfile
    container_name: orm-member-service
    volumes:
      - ./ORM-member-service:/app
    ports:
      - "${ORM_MEMBER_SERVICE_PORT}:${ORM_MEMBER_SERVICE_PORT}"
    env_file:
      - .env
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - COMMUNITY_DATABASE_MEMBER=${COMMUNITY_DATABASE_MEMBER}
    links:
      - mongodb
    depends_on:
      - mongodb            

  orm-post-service:
    restart: always
    build:
      context: ./ORM-post-service
      dockerfile: Dockerfile
    container_name: orm-post-service
    volumes:
      - ./ORM-post-service:/app
    ports:
      - "${ORM_POST_SERVICE_PORT}:${ORM_POST_SERVICE_PORT}"
    env_file:
      - .env
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - COMMUNITY_DATABASE_BOARD=${COMMUNITY_DATABASE_BOARD}
    links:
      - mongodb
    depends_on:
      - mongodb


  orm-comment-service:
    restart: always
    build:
      context: ./ORM-comment-service
      dockerfile: Dockerfile
    container_name: orm-comment-service
    volumes:
      - ./ORM-comment-service:/app
    ports:
      - "${ORM_COMMENT_SERVICE_PORT}:${ORM_COMMENT_SERVICE_PORT}"
    env_file:
      - .env
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - COMMUNITY_DATABASE_COMMENT=${COMMUNITY_DATABASE_COMMENT}
    links:
      - mongodb
    depends_on:
      - mongodb

  orm-log-service:
    restart: always
    build:
      context: ./ORM-log-service
      dockerfile: Dockerfile
    container_name: orm-log-service
    volumes:
      - ./ORM-log-service:/app
    ports:
      - "${ORM_LOG_SERVICE_PORT}:${ORM_LOG_SERVICE_PORT}"
    env_file:
      - .env
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - COMMUNITY_DATABASE_COMMENT=${COMMUNITY_DATABASE_COMMENT}
    links:
      - mongodb
    depends_on:
      - mongodb


  orm-message-service:
    restart: always
    build:
      context: ./ORM-message-service
      dockerfile: Dockerfile
    container_name: orm-message-service
    volumes:
      - ./ORM-message-service:/app
    ports:
      - "${ORM_MESSAGE_SERVICE_PORT}:${ORM_MESSAGE_SERVICE_PORT}"
    env_file:
      - .env
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - COMMUNITY_DATABASE_COMMENT=${COMMUNITY_DATABASE_COMMENT}
    links:
      - mongodb
    depends_on:
      - mongodb

  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    restart: unless-stopped

  mysql:
    container_name: mysql
    image: mysql:8.0.33
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: default
      MYSQL_DATABASE: user
    restart: unless-stopped

  mongodb:
    restart: unless-stopped
    ports:
      - '27017:27017'
    container_name: mongodb
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    image: mongo  
    volumes:
      - ./mongodb:/data/db
